<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need) Exercises</span></div>

## Excercise 1

1. Both lists and arrays are used to store data in a specific order. *Subsetting, indexing and slicing can all be aplied to lists and arrays*
2. List can hold elements of different types (such as string, integer, float etc) but arrays can only hold elements of one type.
3. A dictionary pairs a key and a value.

## Excercise 2

In [1]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])   # Prints 'a1'
print(py_list[2])   # Prints 'c3'
print(py_list[4])   # Prints 'e5'
print(py_list[6])   # Prints 'g7'
print(py_list[8])   # Prints 'i9'

a1
c3
e5
g7
i9


In [5]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0:9:2]) #0 indicates the start, 9 indicates the end of the list, 2 indicates the interval

['a1', 'c3', 'e5', 'g7', 'i9']


## Excercise 3

In [6]:
elements = ['Hydrogen',
            'Helium', 'Lithium',
            'Beryllium', 'Boron', 'Carbon',
            'Nitrogen', 'Oxygen',
            'Fluorine',
            'Neon']

In [7]:
print(elements[4])

Boron


In [8]:
print(elements[-4])

Nitrogen


## Excercise 4

In [10]:
import numpy as np

In [13]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]

np_array = np.array(numbers)

In [15]:
np_array ==1

array([False, False,  True, False, False,  True, False, False, False,
        True, False, False, False, False, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False,  True, False,  True, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False])

In [17]:
(np_array == 1).sum()

np.int64(9)

Therefore, there is 9 ones in the list above.

## Excercise 5

In [20]:
x_1 = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
x_2 = [1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

np_1=np.array(x_1)
np_2=np.array(x_2)

In [24]:
print('Mean of x_1 is',(np_1).mean())
print('Mean of x_2 is',(np_2).mean())

Mean of x_1 is 38.5
Mean of x_2 is 302.5


In [25]:
print('Standard deviation of x_1 is',(np_1).std())
print('Standard deviation of x_2 is',(np_2).std())

Standard deviation of x_1 is 32.41990129534635
Standard deviation of x_2 is 326.0893282522444


In [27]:
a = np_1 - 38.5
print(a)

[-37.5 -34.5 -29.5 -22.5 -13.5  -2.5  10.5  25.5  42.5  61.5]


In [50]:
b = np_2 - 302.5
print(b)

[-301.5 -294.5 -275.5 -238.5 -177.5  -86.5   40.5  209.5  426.5  697.5]


In [56]:
e = (a*b)
print(e)

[11306.25 10160.25  8127.25  5366.25  2396.25   216.25   425.25  5342.25
 18126.25 42896.25]


In [32]:
c = np.array(a)**2
print(c)

[1406.25 1190.25  870.25  506.25  182.25    6.25  110.25  650.25 1806.25
 3782.25]


In [54]:
d = np.array(b)**2
print(d)

[ 90902.25  86730.25  75900.25  56882.25  31506.25   7482.25   1640.25
  43890.25 181902.25 486506.25]


In [62]:
f = c.sum()*d.sum()
print(f)

11176261346.25


In [61]:
print(e.sum()/np.sqrt(f))

0.9871796626270701
