<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

## Exercise 1

| **Term**  | **Brief Description** |
|:----|:-----|
| Subsetting  | Refers to selecting elements in a list or array     |
| Indexing  | Refers to selecting one element in a list or array     |
| Slicing  | Refers to selecting a range of elements in a list or array     |
| Masking  | Refers to selecting specific elements of an array that meet a certain criteria     |

## Exercise 2

In [10]:
import numpy as np

In [13]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [31]:
numbers_only = np_array_2d[:,0]
numbers_only

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

In [32]:
numbers_only_1=numbers_only.astype(int) #used to cast or convert the elements of an array to a different data type
numbers_only_1

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [33]:
numbers_only_2=numbers_only_1%2
numbers_only_2

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [34]:
my_mask = numbers_only_2 > 0
my_mask

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [26]:
np_array_2d[my_mask,1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

In [27]:
print(np_array_2d[my_mask,1])

['A' 'C' 'E' 'G' 'I']


## Exercise 3

In [55]:
array = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

In [56]:
array[array < 50] = -1  
array[array > 50] = 1 
array[array == 50] = 0 #only works for int values

print(array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
