<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [8]:
print('\033[91m'+'somewhere'+'\033[0m')
print('\033[93m'+'over'+'\033[0m')
print('\033[92m'+'the'+'\033[0m')
print('\033[94m'+'rainbow'+'\033[0m')
print('\033[96m'+'way'+'\033[0m')
print('\033[36m'+'up'+'\033[0m')
print('\033[95m'+'high'+'\033[0m')

somewhere
over
the
rainbow
way
up
high


In [1]:
import numpy as np

In [2]:
np.sqrt(4)

np.float64(2.0)

In [68]:
print(np.sqrt(4))

2.0


In [67]:
print(int(np.sqrt(4)))

2


In [3]:
print(np.pi)

3.141592653589793


# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

Python list

In [3]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

Numpy arrays

In [4]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

Dictionary

In [5]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

## 1.2 Accessing data from a list (or array)

In [8]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [9]:
py_real_names[0]

'Natasha Romanoff'

In [13]:
py_super_names[0]

'Black Widow'

In [15]:
py_super_names[-1]

'Doctor Strange'

In [16]:
py_real_names[-2]

'Tony Stark'

In [11]:
seventeen = ["one", "two", "three"]

In [12]:
seventeen[1]

'two'

## 1.3 Accessing data from a dictionary

In [29]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

In [18]:
superhero_info["Natasha Romanoff"]

'Black Widow'

In [19]:
superhero_info["Iron Man"]

KeyError: 'Iron Man'

In [20]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [21]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [22]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

In [25]:
py_superhero_info[1]

['Tony Stark', 'Iron Man']

In [26]:
py_superhero_info[1][0]

'Tony Stark'

In [1]:
py_superhero_info[1,0]

NameError: name 'py_superhero_info' is not defined

# 2 Lists vs. Arrays

## 2.1 Size

In [3]:
import numpy as np

In [4]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [6]:
len(py_list_2d)

10

In [7]:
len(np_array_2d)

10

In [8]:
np_array_2d.shape

(10, 2)

In [37]:
py_list_2d[3]

[4, 'D']

In [35]:
py_list_2d[3][0]

4

In [36]:
py_list_2d[3][1]

'D'

In [9]:
np_array_2d[3]

array(['4', 'D'], dtype='<U21')

In [71]:
np_array_2d[3,1]

np.str_('D')

In [11]:
str(np_array_2d[3,1])

'D'

## 2.2 Arrays are fussy about type

In [41]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [42]:
py_list

[1, 1.5, 'A']

In [43]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [12]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [45]:
np_array + 10

array([11, 12, 13, 14, 15])

In [46]:
py_list + 10 

TypeError: can only concatenate list (not "int") to list

In [54]:
py_list+[10]

[1, 2, 3, 4, 5, 10]

In [13]:
np_array*10

array([10, 20, 30, 40, 50])

In [15]:
py_list*[10]

TypeError: can't multiply sequence by non-int of type 'list'

In [16]:
py_list*10

[1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5]

In [69]:
py_alphabet = ['A', 'B', 'C', 'D', 'E']
np_array_alphabet = np.array(py_alphabet) 

In [56]:
np_array_alphabet

array(['A', 'B', 'C', 'D', 'E'], dtype='<U1')

In [57]:
np_array_alphabet + 10

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U1'), dtype('int64')) -> None

In [60]:
[1,2]*10

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

## 2.4 Adding another list

In [17]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [20]:
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [19]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [21]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [22]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [23]:
np_array*2

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [24]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [25]:
py_list**2                      # Won't work!  

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [26]:
np_array**2

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [27]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [28]:
py_list == 3

False

In [31]:
py_list == [1,2,3,4,5]

True

In [29]:
np_array == 3

array([False, False,  True, False, False])

In [30]:
np_array > 3  

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [32]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [33]:
sum(py_list) 

15

In [34]:
max(py_list)

5

In [35]:
min(py_list)

1

In [36]:
np_array.sum()

np.int64(15)

In [37]:
np_array.max()

np.int64(5)

In [38]:
np_array.min()

np.int64(1)

In [39]:
np_array.mean()

np.float64(3.0)

In [40]:
np_array.std()

np.float64(1.4142135623730951)

## Footnotes