<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

In [2]:
import numpy as np

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [5]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR x = np_array

In [6]:
x[0]

'a1'

In [7]:
x[-1]

'j10'

In [10]:
x[0:3]  #0,1,2

['a1', 'b2', 'c3']

In [11]:
x[1:6]  #1,2,3,4,5

['b2', 'c3', 'd4', 'e5', 'f6']

In [12]:
x[1:6:2]  #1,3,5

['b2', 'd4', 'f6']

In [13]:
x[5:]

['f6', 'g7', 'h8', 'i9', 'j10']

In [17]:
x[:5] #0,1,2,3,4

['a1', 'b2', 'c3', 'd4', 'e5']

In [18]:
x[5:2:-1] #5,4,3

['f6', 'e5', 'd4']

In [19]:
x[::-1]

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

In [22]:
len(x)

10

## 1.2 Arrays only | Subsetting by masking

In [23]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [27]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [28]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [29]:
np_array[~(np_array > 3)]                 # '~' means 'NOT'

array([1, 2, 3])

In [30]:
np_array[(np_array > 3) & (np_array < 8)] # '&' means 'AND'

array([4, 5, 6, 7])

In [32]:
np_array[3 < np_array < 8]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [33]:
np_array[(np_array < 3) | (np_array > 8)] # '|' means 'OR'

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [34]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [37]:
py_list_2d[3][0]

4

In [36]:
np_array_2d[3, 0]

np.str_('4')

In [38]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [39]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [42]:
py_list_2d[:3][0] #out of 0,1,2 give me 0

[1, 'A']

In [44]:
np_array_2d[:3, 0] #give me 0 OF 0,1,2

array(['1', '2', '3'], dtype='<U21')

In [45]:
py_list_2d[3:6][0] #out of 3,4,5,6 give me 0

[4, 'D']

In [46]:
np_array_2d[3:6, 0] #give me 0 OF 3,4,5

array(['4', '5', '6'], dtype='<U21')

In [47]:
np_array_2d[:, 0] # use : for everything. so, give me 0 OF everything

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

## 1.4 Growing lists

In [48]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [51]:
y=np.array([1,2])

In [52]:
y*5

array([ 5, 10])

In [53]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [54]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [55]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

**extend() vs append()**

In [56]:
x = [1, 2, 3]
x += [4, 5, 6]
x

[1, 2, 3, 4, 5, 6]

In [57]:
x=[1, 2, 3]
x.extend([4, 5, 6])
x

[1, 2, 3, 4, 5, 6]

In [58]:
x=[1, 2, 3]
x.append([4, 5, 6])
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

In [59]:
a=(1, 2, 3)     # Define tuple

In [60]:
print(a[0])    # Access data

1


In [61]:
a[0]+= [10]

TypeError: unsupported operand type(s) for +=: 'int' and 'list'

In [75]:
b=[10,20,30]

In [76]:
print(b[1])

20


In [78]:
b[1] += 1
b

[10, 21, 30]

## 1.6 Be VERY careful when copying

In [80]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

In [82]:
y

[1, 2, 3]

In [83]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

In [84]:
z

[1, 2, 3]

## Footnotes